id: a5c0f92f8c3a4ef58969cd16af26f20b
initial_creation_type: ocr
source_metadata:
  volumes:
    1027ee5c69ba4bf5a35e20dc56143713:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
